apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: realtor_Assignment
  description: Sample Component for realtor assignment.
  annotations:
    github.com/project-slug: Atharva-Sandesh-brillio/realtor_Assignment
    backstage.io/techdocs-ref: url:https://github.com/Atharva-Sandesh-brillio/realtor_Assignment/blob/main/README.md
tags:
    - frontend
    - React
spec:
  type: service
  lifecycle: production
  owner: "guests"
  system: realtor_system
  providesApis:
    - Users-api
  consumesApis:
    - Photos-api
  dependsOn:
    - service:example-service
  links:
    - url: https://jsonplaceholder.typicode.com/users
      title: Users API
      type: provided
    - url: https://jsonplaceholder.typicode.com/photos
      title: Photos API
      type: consumed
  ci/cd:
    - github-actions
