apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: photos-api
  description: API for managing photos
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition: |
    openapi: 3.0.0
    info:
      title: Photos API
      version: 1.0.0
    paths:
      /photos:
        get:
          summary: List all photos
          responses:
            '200':
              description: A list of photos
