apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-api
  description: API for managing users
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition: |
    openapi: 3.0.0
    info:
      title: Users API
      version: 1.0.0
    paths:
      /users:
        get:
          summary: List all users
          responses:
            '200':
              description: A list of users
