version: 2.1

import:
  - anchors.yml
  - jobs.yml
  - commands.yml
  - executors.yml

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
