# .circleci/config.yml

version: 2.1
orbs:
  node: circleci/node@5

# Import executors
import:
  - .circleci/executors/executors.yml

# Import jobs
import:
  - .circleci/jobs/jobs.yml

# Import commands
import:
  - .circleci/commands/commands.yml

# Import workflows
import:
  - .circleci/workflows/workflows.yml

# Import anchors (if any)
import:
  - .circleci/anchors/anchors.yml
