# .circleci/jobs/jobs.yml

jobs:
  test-node:
    executor: default-executor
    steps:
      - checkout
      - install-packages
      - run-tests

  build-node:
    executor: default-executor
    steps:
      - checkout
      - install-packages
      - build-project
      - create-artifacts-dir
      - copy-artifacts
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - deploy
